import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="relative min-h-screen font-serif text-white">
        {/* Background image layer */}
        <div className="absolute inset-0 bg-[url('/images/bg1.jpeg')] bg-cover bg-center" />
        
        {/* Dark overlay */}
        <div className="absolute inset-0 bg-black/40" />

        {/* Page content */}
        <main className="relative z-10">{children}</main>
      </body>
    </html>
  )
}