"""Add created_at to tasks table

Revision ID: 110a223f1d04
Revises: fda945a9616d
Create Date: 2025-07-29 15:27:16.417188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '110a223f1d04'
down_revision: Union[str, Sequence[str], None] = 'fda945a9616d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('ix_tasks_title'), table_name='tasks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tasks_title'), 'tasks', ['title'], unique=False)
    op.drop_column('tasks', 'created_at')
    # ### end Alembic commands ###
