"""Edited created_at

Revision ID: 2e69058c028b
Revises: 9aed1fb1dfe9
Create Date: 2025-07-29 16:23:33.431719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e69058c028b'
down_revision: Union[str, Sequence[str], None] = '9aed1fb1dfe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('focus_sessions', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_column('focus_sessions', 'timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('focus_sessions', sa.Column('timestamp', sa.DATETIME(), nullable=True))
    op.drop_column('focus_sessions', 'created_at')
    # ### end Alembic commands ###
